---
- name: Stop the blockchain node service.
  ansible.builtin.systemd_service:
    name: "{{ blockchain_node_company }}{{ item }}"
    daemon_reload: true
    state: stopped
  register: blockchain_node_stop_service
  failed_when:
    - blockchain_node_stop_service.failed == true
    - '"Could not find the requested service" not in blockchain_node_stop_service.msg'
  with_sequence: start={{ blockchain_node_count + 1 }} end={{ blockchain_node_cleanup }} format='%03d'

- name: Remove the blockchain node service.
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ blockchain_node_company }}{{ item }}.service"
    state: absent
  with_sequence: start={{ blockchain_node_count + 1 }} end={{ blockchain_node_cleanup }} format='%03d'

- name: Remove user accounts.
  ansible.builtin.user:
    name: "{{ blockchain_node_user }}{{ item }}"
    remove: true
    state: absent
  with_sequence: start={{ blockchain_node_count + 1 }} end={{ blockchain_node_cleanup }} format='%03d'
